### ISSUE TITLE
May I know how to use this under Windows?

### ISSUE THREAD

**Issue by liqilei** [RasmusHaugaard/collage#1]
Hi,

Thanks for your work. 
I tried to use this via 'pip install image-grid', but when I executed it under Windows, I got 'image-grid' is not recognized as an internal or external command'. Just wanna make sure if this can also work under Windows environment?

Thanks

**Comment by egabrum** [comment]
This worked for me:
`image-grid.py -f ./`

**Comment by liqilei** [comment]
> This worked for me:
> `image-grid.py -f ./`

Thanks for your reply.
